### ISSUE TITLE
Open html file instead of downloading

### ISSUE THREAD

**Issue by penguinsam** [pldubouilh/gossa#83]
I intended to host gossa to serve all my HTMLs I downloaded by SingleFile, but just found for html its default action is to download.

Can make an option or config so that it can render the html as web browser?

**Comment by pldubouilh** [comment]
if you're interested doing a PR for that, I'd accept it - it's just about adding a statement [here](https://github.com/pldubouilh/gossa-ui/blob/5ec0a804c908654225745ffc8e387859d337c846/script.js#L87) to let the browser follow the link naturally instead of executing `dl` :)
otherwise I'll cover that next release, but it might take a while.

**Comment by penguinsam** [comment]
Yes please. It really helps!
