### ISSUE TITLE
permission denied

### ISSUE THREAD

**Issue by xiejiulong** [pldubouilh/gossa#92]
I run gossa in docker, and the run cmd is :
`sudo docker run -v ~/LocalDirToShare:/shared -p 8001:8001 pldubouilh/gossa`
but when i upload a file,for example css file, the docker log show me:
` error [upload %2Fstyle.css] open /shared/style.css: permission denied.`

i tried other kind file , same err, why?

**Comment by xiejiulong** [comment]
![image](https://github.com/pldubouilh/gossa/assets/13202893/1af16989-7dc0-4ac5-a109-14037aa74240)

**Comment by pldubouilh** [comment]
hey - thanks for the report ! 
So this happens when `~/LocalDirToShare` is _not_ created before calling `sudo docker ...`. Then Docker creates the folder as root, making gossa unable to access it. Just `rm -rf ~/LocalDirToShare` and then `mkdir ~/LocalDirToShare` before you run the docker invoke. I'll amend the main docs to reflect this :+1:

**Comment by pldubouilh** [comment]
hm odd, this is working just fine on my setup...
maybe `ls -lha ~/LocalDirToShare` see who's the owner and what are the perms ?

**Comment by xiejiulong** [comment]
**I solved the problem:**
after exec 
`sudo docker run -v ~/LocalDirToShare:/shared -p 8001:8001 pldubouilh/gossa`
**then, go to the container exec:**
`chmod 777 /root/shared`
then exit the container.
now, I can upload any file to gossa.
thanks a lot.

But unfortunately, I don't know why the docker or gossa has no permission to access the dir named "~/LocalDirToShare"  in host machine map to "/root/share" in the container
